### ISSUE TITLE
Broken Weather's Audio Streaming

### ISSUE THREAD

**Issue by DocNITE** [Simple-Station/Einstein-Engines#1285]
# Description

For some reason WeatherSystem create too many audio streams and spam with it, until OpenAL will `Out Of Memory`

Error message:
```
[ERRO] clyde.oal: Failed to generate source. Too many simultaneous audio streams?    at System.Environment.get_StackTrace()
   at Robust.Client.Audio.AudioManager.CreateAudioSource(AudioStream stream) in /home/docnite/Desktop/C#/EE-PRs/RobustToolbox/Robust.Client/Audio/AudioManager.Public.cs:line 290
   at Robust.Client.Audio.AudioSystem.LoadStream[T](Entity`1 entity, T stream) in /home/docnite/Desktop/C#/EE-PRs/RobustToolbox/Robust.Client/Audio/AudioSystem.cs:line 623
   at Robust.Client.Audio.AudioSystem.CreateAndStartPlayingStream(Nullable`1 audioParams, AudioStream stream) in /home/docnite/Desktop/C#/EE-PRs/RobustToolbox/Robust.Client/Audio/AudioSystem.cs:line 665
   at Robust.Client.Audio.AudioSystem.PlayGlobal(String filename, Nullable`1 audioParams, Boolean recordReplay) in /home/docnite/Desktop/C#/EE-PRs/RobustToolbox/Robust.Client/Audio/AudioSystem.cs:line 494
   at Content.Client.Weather.WeatherSystem.Run(EntityUid uid, WeatherData weather, WeatherPrototype weatherProto, Single frameTime) in /home/docnite/Desktop/C#/EE-PRs/Content.Client/Weather/WeatherSystem.cs:line 30
   at Content.Shared.Weather.SharedWeatherSystem.Update(Single frameTime) in /home/docnite/Desktop/C#/EE-PRs/Content.Shared/Weather/SharedWeatherSystem.cs:line 147
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTime, Boolean noPredictions) in /home/docnite/Desktop/C#/EE-PRs/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 306
   at Robust.Shared.GameObjects.EntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in /home/docnite/Desktop/C#/EE-PRs/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 273
   at Robust.Client.GameObjects.ClientEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in /home/docnite/Desktop/C#/EE-PRs/RobustToolbox/Robust.Client/GameObjects/ClientEntityManager.cs:line 194
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in /home/docnite/Desktop/C#/EE-PRs/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 284
   at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in /home/docnite/Desktop/C#/EE-PRs/RobustToolbox/Robust.Client/GameController/GameController.cs:line 552
   at Robust.Shared.Timing.GameLoop.Run() in /home/docnite/Desktop/C#/EE-PRs/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 240
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in /home/docnite/Desktop/C#/EE-PRs/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 162
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in /home/docnite/Desktop/C#/EE-PRs/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 147
   at Robust.Client.GameController.<>c__DisplayClass105_0.<Run>b__0() in /home/docnite/Desktop/C#/EE-PRs/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 106m.Environment.get_StackTrace()
```

# Reproduction

1. Open game
2. Type `weather (map_id) (weather_proto)`
3. See errors spaming

# Media

https://github.com/user-attachments/assets/3d333408-19af-4098-ba72-5207fa58c1b5

(sorry for bad quality, i have some issues with recording it in 10 MB size)

**Comment by DocNITE** [comment]
bump
