### ISSUE TITLE
Bug with metadata component

### ISSUE THREAD

**Issue by Evgencheg** [Simple-Station/Einstein-Engines#950]
some errors happen with metadata component. Idk how to reproduce this, just happens when playing.

```
2024-09-22T23:05:15.8887159+03:00 [ERRO] resolve: Can't resolve "Robust.Shared.GameObjects.MetaDataComponent" on entity 49685!
   at Content.Shared.Weapons.Ranged.Components.TargetedProjectileComponent.TargetedProjectileComponent_AutoNetworkSystem.OnGetState(EntityUid uid, TargetedProjectileComponent component, ComponentGetState& args) in /home/runner/work/Lost-Paradise/Lost-Paradise/Content.Shared/Robust.Shared.CompNetworkGenerator/Robust.Shared.CompNetworkGenerator.ComponentNetworkGenerator/TargetedProjectileComponent_CompNetwork.g.cs:line 31
   at Robust.Shared.GameObjects.EntityEventBus.Robust.Shared.GameObjects.IDirectedEventBus.RaiseComponentEvent[TEvent](IComponent component, TEvent& args) in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 156
   at Robust.Shared.GameObjects.EntityManager.GetComponentState(IEventBus eventBus, IComponent component, ICommonSession session, GameTick fromTick) in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Components.cs:line 1407
   at Robust.Server.GameStates.PvsSystem.GetEntityState(ICommonSession player, EntityUid entityUid, GameTick fromTick, MetaDataComponent meta) in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Server/GameStates/PvsSystem.GetStates.cs:line 52
   at Robust.Server.GameStates.PvsSystem.AddPvsChunk(PvsChunk chunk, Single distance, PvsSession session) in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Server/GameStates/PvsSystem.ToSendSet.cs:line 61
   at Robust.Server.GameStates.PvsSystem.GetEntityStates(PvsSession session) in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Server/GameStates/PvsSystem.cs:line 330
   at Robust.Server.GameStates.PvsSystem.ComputeSessionState(PvsSession session) in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Server/GameStates/PvsSystem.Session.cs:line 88
   at Robust.Server.GameStates.PvsSystem.SendStateUpdate(ICommonSession session, PvsThreadResources resources) in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Server/GameStates/PvsSystem.Session.cs:line 32
   at Robust.Server.GameStates.PvsSystem.<>c__DisplayClass73_0.<SendStates>g__SendPlayer|0(Int32 i, ParallelLoopState state, PvsThreadResources resource) in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Server/GameStates/PvsSystem.cs:line 219
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```
```
2024-09-22T23:05:50.7320680+03:00 [ERRO] resolve: Can't resolve "Robust.Shared.GameObjects.MetaDataComponent" on entity 193194!
   at Content.Shared.Buckle.Components.BuckleComponent.BuckleComponent_AutoNetworkSystem.OnGetState(EntityUid uid, BuckleComponent component, ComponentGetState& args) in /home/runner/work/Lost-Paradise/Lost-Paradise/Content.Shared/Robust.Shared.CompNetworkGenerator/Robust.Shared.CompNetworkGenerator.ComponentNetworkGenerator/BuckleComponent_CompNetwork.g.cs:line 34
   at Robust.Shared.GameObjects.EntityEventBus.Robust.Shared.GameObjects.IDirectedEventBus.RaiseComponentEvent[TEvent](IComponent component, TEvent& args) in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 156
   at Robust.Shared.GameObjects.EntityManager.GetComponentState(IEventBus eventBus, IComponent component, ICommonSession session, GameTick fromTick) in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Components.cs:line 1407
   at Robust.Server.GameStates.PvsSystem.GetEntityState(ICommonSession player, EntityUid entityUid, GameTick fromTick, MetaDataComponent meta) in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Server/GameStates/PvsSystem.GetStates.cs:line 52
   at Robust.Server.GameStates.PvsSystem.AddPvsChunk(PvsChunk chunk, Single distance, PvsSession session) in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Server/GameStates/PvsSystem.ToSendSet.cs:line 61
   at Robust.Server.GameStates.PvsSystem.GetEntityStates(PvsSession session) in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Server/GameStates/PvsSystem.cs:line 330
   at Robust.Server.GameStates.PvsSystem.ComputeSessionState(PvsSession session) in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Server/GameStates/PvsSystem.Session.cs:line 88
   at Robust.Server.GameStates.PvsSystem.SendStateUpdate(ICommonSession session, PvsThreadResources resources) in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Server/GameStates/PvsSystem.Session.cs:line 32
   at Robust.Server.GameStates.PvsSystem.<>c__DisplayClass73_0.<SendStates>g__SendPlayer|0(Int32 i, ParallelLoopState state, PvsThreadResources resource) in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Server/GameStates/PvsSystem.cs:line 219
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```
```
2024-09-22T23:02:00.1627471+03:00 [ERRO] resolve: Can't resolve "Robust.Shared.GameObjects.MetaDataComponent" on entity 432646!
   at Content.Shared.Shuttles.Components.ShuttleDestinationCoordinatesComponent.ShuttleDestinationCoordinatesComponent_AutoNetworkSystem.OnGetState(EntityUid uid, ShuttleDestinationCoordinatesComponent component, ComponentGetState& args) in /home/runner/work/Lost-Paradise/Lost-Paradise/Content.Shared/Robust.Shared.CompNetworkGenerator/Robust.Shared.CompNetworkGenerator.ComponentNetworkGenerator/ShuttleDestinationCoordinatesComponent_CompNetwork.g.cs:line 31
   at Robust.Shared.GameObjects.EntityEventBus.Robust.Shared.GameObjects.IDirectedEventBus.RaiseComponentEvent[TEvent](IComponent component, TEvent& args) in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 156
   at Robust.Shared.GameObjects.EntityManager.GetComponentState(IEventBus eventBus, IComponent component, ICommonSession session, GameTick fromTick) in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Components.cs:line 1407
   at Robust.Server.GameStates.PvsSystem.GetEntityState(ICommonSession player, EntityUid entityUid, GameTick fromTick, MetaDataComponent meta) in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Server/GameStates/PvsSystem.GetStates.cs:line 52
   at Robust.Server.GameStates.PvsSystem.AddPvsChunk(PvsChunk chunk, Single distance, PvsSession session) in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Server/GameStates/PvsSystem.ToSendSet.cs:line 61
   at Robust.Server.GameStates.PvsSystem.GetEntityStates(PvsSession session) in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Server/GameStates/PvsSystem.cs:line 330
   at Robust.Server.GameStates.PvsSystem.ComputeSessionState(PvsSession session) in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Server/GameStates/PvsSystem.Session.cs:line 88
   at Robust.Server.GameStates.PvsSystem.SendStateUpdate(ICommonSession session, PvsThreadResources resources) in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Server/GameStates/PvsSystem.Session.cs:line 32
   at Robust.Server.GameStates.PvsSystem.<>c__DisplayClass73_0.<SendStates>g__SendPlayer|0(Int32 i, ParallelLoopState state, PvsThreadResources resource) in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Server/GameStates/PvsSystem.cs:line 219
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by Mnemotechnician** [comment]
Metadata comp is required and exists on every entity; if you don't have it, there's an issue in your code (likely a server-side component marked as networked).

**Comment by Evgencheg** [comment]
> Metadata comp is required and exists on every entity; if you don't have it, there's an issue in your code (likely a server-side component marked as networked).

Sooo… how to check if it doesnt exists on some entities?

**Comment by Evgencheg** [comment]
> I don't know if this even can be reproduced on EE Master, and I've never seen this in my dev environment or in any of my downstreams that I'm active on, so it might be local only to your downstream.

it happens when someone buckling and other things. Just soooo much players use something so it just errors somewhere.

**Comment by Aidenkrz** [comment]
This happens a LOT on goob lrp, also have no clue what causes it.
