### ISSUE TITLE
Can't resolve "Content.Server.IgnitionSource.IgnitionSourceComponent"

### ISSUE THREAD

**Issue by Evgencheg** [Simple-Station/Einstein-Engines#951]
```
2024-09-22T22:55:03.0815464+03:00 [ERRO] system.ignition_source: Can't resolve "Content.Server.IgnitionSource.IgnitionSourceComponent" on entity Бригита-Чалари (53719/n53719, MobReptilian, Gleem)!
   at Content.Server.Atmos.EntitySystems.FlammableSystem.Extinguish(EntityUid uid, FlammableComponent flammable) in /home/runner/work/Lost-Paradise/Lost-Paradise/Content.Server/Atmos/EntitySystems/FlammableSystem.cs:line 301
   at Content.Server.Chemistry.ReagentEffects.ExtinguishReaction.Effect(ReagentEffectArgs args) in /home/runner/work/Lost-Paradise/Lost-Paradise/Content.Server/Chemistry/ReagentEffects/ExtinguishReaction.cs:line 19
   at Content.Shared.Chemistry.ReactiveSystem.ReactionEntity(EntityUid uid, ReactionMethod method, ReagentPrototype proto, ReagentQuantity reagentQuantity, Solution source) in /home/runner/work/Lost-Paradise/Lost-Paradise/Content.Shared/Chemistry/ReactiveSystem.cs:line 70
   at Content.Shared.Chemistry.ReactiveSystem.ReactionEntity(EntityUid uid, ReactionMethod method, ReagentQuantity reagentQuantity, Solution source) in /home/runner/work/Lost-Paradise/Lost-Paradise/Content.Shared/Chemistry/ReactiveSystem.cs:line 31
   at Content.Server.Fluids.EntitySystems.PuddleSystem.TrySplashSpillAt(EntityUid uid, EntityCoordinates coordinates, Solution solution, EntityUid& puddleUid, Boolean sound, Nullable`1 user) in /home/runner/work/Lost-Paradise/Lost-Paradise/Content.Server/Fluids/EntitySystems/PuddleSystem.cs:line 587
   at Content.Server.Destructible.Thresholds.Behaviors.SpillBehavior.Execute(EntityUid owner, DestructibleSystem system, Nullable`1 cause) in /home/runner/work/Lost-Paradise/Lost-Paradise/Content.Server/Destructible/Thresholds/Behaviors/SpillBehavior.cs:line 33
   at Content.Server.Destructible.Thresholds.DamageThreshold.Execute(EntityUid owner, DestructibleSystem system, IEntityManager entityManager, Nullable`1 cause) in /home/runner/work/Lost-Paradise/Lost-Paradise/Content.Server/Destructible/Thresholds/DamageThreshold.cs:line 92
   at Content.Server.Destructible.DestructibleSystem.Execute(EntityUid uid, DestructibleComponent component, DamageChangedEvent args) in /home/runner/work/Lost-Paradise/Lost-Paradise/Content.Server/Destructible/DestructibleSystem.cs:line 84
   at Robust.Shared.GameObjects.EntityEventBus.DispatchOrderedEvents(Unit& eventArgs, ValueList`1& found) in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Ordering.cs:line 47
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 177
   at Content.Shared.Damage.DamageableSystem.DamageChanged(EntityUid uid, DamageableComponent component, DamageSpecifier damageDelta, Boolean interruptsDoAfters, Nullable`1 origin) in /home/runner/work/Lost-Paradise/Lost-Paradise/Content.Shared/Damage/Systems/DamageableSystem.cs:line 112
   at Content.Shared.Damage.DamageableSystem.TryChangeDamage(Nullable`1 uid, DamageSpecifier damage, Boolean ignoreResistances, Boolean interruptsDoAfters, DamageableComponent damageable, Nullable`1 origin) in /home/runner/work/Lost-Paradise/Lost-Paradise/Content.Shared/Damage/Systems/DamageableSystem.cs:line 190
   at Content.Server.Explosion.EntitySystems.ExplosionSystem.ProcessEntity(EntityUid uid, MapCoordinates epicenter, DamageSpecifier originalDamage, Single throwForce, String id, TransformComponent xform) in /home/runner/work/Lost-Paradise/Lost-Paradise/Content.Server/Explosion/EntitySystems/ExplosionSystem.Processing.cs:line 440
   at Content.Server.Explosion.EntitySystems.ExplosionSystem.ExplodeSpace(BroadphaseComponent lookup, Matrix3 spaceMatrix, Matrix3 invSpaceMatrix, Vector2i tile, Single throwForce, DamageSpecifier damage, MapCoordinates epicenter, HashSet`1 processed, String id) in /home/runner/work/Lost-Paradise/Lost-Paradise/Content.Server/Explosion/EntitySystems/ExplosionSystem.Processing.cs:line 321
   at Content.Server.Explosion.EntitySystems.Explosion.Process(Int32 processingTarget) in /home/runner/work/Lost-Paradise/Lost-Paradise/Content.Server/Explosion/EntitySystems/ExplosionSystem.Processing.cs:line 822
   at Content.Server.Explosion.EntitySystems.ExplosionSystem.Update(Single frameTime) in /home/runner/work/Lost-Paradise/Lost-Paradise/Content.Server/Explosion/EntitySystems/ExplosionSystem.Processing.cs:line 133
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTime, Boolean noPredictions) in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 306
   at Robust.Shared.GameObjects.EntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 247
   at Robust.Server.GameObjects.ServerEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 195
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Server/BaseServer.cs:line 702
   at Robust.Shared.Timing.GameLoop.Run() in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 235
   at Robust.Server.BaseServer.MainLoop() in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Server/BaseServer.cs:line 569
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Server/Program.cs:line 76
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Server/Program.cs:line 44
   at Robust.Server.Program.Main(String[] args) in /home/runner/work/Lost-Paradise/Lost-Paradise/RobustToolbox/Robust.Server/Program.cs:line 25
```
idk how to reproduce sooo... just error

**Comment by Peptide90** [comment]
Having this same error now after pulling upstream from the 16th. Causing a map to not load.

**Comment by VMSolidus** [comment]
> Having this same error now after pulling upstream from the 16th. Causing a map to not load.

Clarify, is it a specific map, or is it all maps?

**Comment by Peptide90** [comment]
> > Having this same error now after pulling upstream from the 16th. Causing a map to not load.
> 
> Clarify, is it a specific map, or is it all maps?

Seems to have fixed itself, it was that same `system.ignition_source: Can't resolve "Content.Server.IgnitionSource.IgnitionSourceComponent" on entity` error but on two mobs which don't have the comp.

**Comment by VMSolidus** [comment]
This is a nonissue, since
